// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Infra.Data.Context;

namespace Project.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190923193217_Projeto")]
    partial class Projeto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project.Domain.Entities.Encargos", b =>
                {
                    b.Property<int>("IdEncargo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BancoDestino")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("ContaDestino")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("CpfCnpjDestino")
                        .IsRequired()
                        .HasMaxLength(14);

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("TipoConta")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<decimal>("ValorEncargo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorLancamento")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdEncargo");

                    b.ToTable("Encargos");
                });

            modelBuilder.Entity("Project.Domain.Entities.Lancamentos", b =>
                {
                    b.Property<int>("IdLancamento")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BancoDestino")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("ContaDestino")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("CpfCnpjDestino")
                        .IsRequired()
                        .HasMaxLength(14);

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("TipoConta")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<decimal>("ValorEncargos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorLancamento")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdLancamento");

                    b.ToTable("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
